# 端口
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system?serverTimezone=GMT%2b8
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    default-encoding: utf-8
    protocol: smtp
    host: smtp.qq.com
    username: 463900948@qq.com
    password: bnyimnrorfcxbhai
    port: 587


#扫描xml文件的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

#打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: E:/System/files/

